sonarqube_master_job:
  stage: test
  only:
  - master
  script:
  - ./gradlew sonarqube -Dsonar.host.url=http://localhost:9000 -Dsonar.login=admin -Dsonar.password=admin

sonarqube_preview_feature_job:
  stage: test
  only:
  - /^feature\/*/
  script:
  - git checkout origin/master
  - git merge $CI_COMMIT_REF --no-commit --no-ff
  - ./gradlew sonarqube -Dsonar.host.url=http://localhost:9000 -Dsonar.login=admin -Dsonar.password=admin -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref=$CI_BUILD_REF_NAME -Dsonar.gitab.project_id=$CI_PROJECT_ID