image: java:8

before_script:
- wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.5.zip
- ./sonarqube-7.5/bin/linux-x86-64/sonar.sh console &
- apt-get update -qq && apt-get install -y -qq git
- git config --global user.email "kali21@masonlive.gmu.edu"
- git config --global user.name "Khalid Ali"

sonarqube_master_job:
  stage: test
  only:
  - master
  script:
  - ./gradlew sonarqube -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.password=$SONAR_PASS

sonarqube_preview_feature_job:
  stage: test
  only:
  - /^feature\/*/
  script:
  - git checkout origin/master
  - git merge $CI_COMMIT_SHA --no-commit --no-ff
  - ./gradlew sonarqube -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.password=$SONAR_PASS -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref=$CI_BUILD_REF_NAME -Dsonar.gitab.project_id=$CI_PROJECT_ID