language: java
sudo: false
install: true

jdk:
- oraclejdk8

addons:
  sonarcloud:
    organization: "khalludi-github" # the key of the org you chose at step #3
    token:
      secure: $SONAR_LOGIN # encrypted value of your token

script:
# other script steps
- ./gradlew sonarqube