spring.jpa:
  hibernate:
    ddl-auto: none
    jdbc.lob.non_contextual_creation: true
  properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  show-sql: true

spring.datasource:
  url: jdbc:postgresql://db:26257/testdb?sslmode=disable
  username: user17
  password:

server:
  ssl:
    enabled: true
    keyStore: file:/etc/cas/tomcat.keystore
    keyStorePassword: changeit
    keyPassword: changeit
  port: 9090

security:
  cas:
    server:
      base-url: https://login.gmu.edu/
    service:
      resolution-mode: dynamic
  require-ssl: true
