spring.jpa:
  hibernate:
    ddl-auto: none
    jdbc.lob.non_contextual_creation: true
    naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  properties.hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
  show-sql: true

spring.datasource:
  url: jdbc:postgresql://localhost:26257/testdb?sslmode=disable
  username: user17
  password:

#logging:
#  level:
#    ROOT: debug
#    sql: debug
#    web: debug

server:
  ssl:
    enabled: true
    keyStore: file:/etc/cas/tomcat.keystore
    keyStorePassword: changeit
    keyPassword: changeit
  port: 9090

security:
  cas:
    server:
      base-url: https://login.gmu.edu/
    service:
      resolution-mode: dynamic
  require-ssl: true